# Nginx Configuration for Traefik dashboard
# Workaround for issue: https://github.com/containous/traefik/issues/5853

server {
  listen 8099 default_server;
  listen [::]:8099 default_server;

  location /dashboard/ {
    proxy_pass http://localhost:8080/dashboard/;

    # --- ADD THESE LINES TO FIX THE WARNING ---
    proxy_buffers 16 16k;
    proxy_buffer_size 32k;
    proxy_busy_buffers_size 64k;
    # ------------------------------------------

    sub_filter '/api' '../api';
    sub_filter_types application/javascript application/x-javascript text/javascript;
    sub_filter_once off;
  }

  location /api {
    proxy_pass http://localhost:8080/api;
    # Optional: You can add the buffers here too if the API responses are large
  }
}
