name: "Kiwix"
description: "Kiwix Encyclopedia"
version: "3.7.0"
slug: "folder"
arch:
  - amd64
  - armv7
url: "https://ghcr.io/kiwix/kiwix-serve:3.7.0"
map:
  - type: share
    read_only: False
  - type: data
    read_only: False
init: "false"
#ingress: "true"
#ingress_port: "8081"
#ingress_stream: true
startup: "application"
ports:
  8080/tcp: "8082"
ports_description:
  8082/tcp: "Kiwix Web Port"
webui: "http://[HOST]:[PORT:8082]"
#options:
#  data_location: "/media/MeTube"
#  data_location: "/media/My_Music/Youtube"
#schema:
#  data_location: "str?"
environment:
  DOWNLOAD_DIR: "/share/zim"
