name: "Kiwix"
description: "Kiwix Encyclopedia"
version: "3.7.1"
slug: kiwix-tools
arch:
  - amd64
  - armv7
  - aarch64
  - armhf
url: "https://www.kiwix.org"
map:
  - type: share
    read_only: False
  - type: data
    read_only: False
init: "false"
#ingress: "true"
#ingress_port: "8081"
#ingress_stream: true
startup: "application"
ports:
  8085: 8080
ports_description:
  8085/tcp: "Kiwix Web Port"
webui: "http://[HOST]:[PORT:8085]"
#volumes:
#  - /share/zim
hassio_api: true
#options:
#  data_location: "/media/MeTube"
#  data_location: "/media/My_Music/Youtube"
#schema:
#  data_location: "str?"
environment:
  data: "/share/zim"
