name: "MeTube TEST"
description: "YouTube music downloader"
version: "0.1.291"
slug: "metube"
arch:
  - amd64
  - armv7
url: "https://github.com/alexta69/metube/pkgs/container/metube"
map:
  - type: media
    read_only: False
#  - type: share
#    read_only: False
  - type: data
    read_only: False
init: "false"
#ingress: "true"
#ingress_port: "8081"
#ingress_stream: true
startup: "application"
ports:
  8081/tcp: "8081"
ports_description:
  8081/tcp: "MeTube Web Port"
webui: "http://[HOST]:[PORT:8081]"
options:
  #data_location: "/media/My_Music/MeTube"
  DOWNLOAD_DIR: "/media/My_Music/MeTube"
schema:
  DOWNLOAD: "str?"
#environment:
#  DOWNLOAD_DIR: "/media/My_Music/MeTube"
